source 'https://rubygems.org'

gem 'sinatra', '~> 2.0.2'
gem 'sinatra-cross_origin', '~> 0.4.0'
gem 'rack', '~> 2.1.4'
gem 'flyml', '~> 0.3.0'
gem 'rake', '~> 12.3.1'
gem 'puma', '~> 4.3.8'
gem 'sentry-raven', '~> 2.7.4'
gem 'newrelic_rpm', '~> 4.8.0.341'
gem "octokit", "~> 4.0"
gem 'httparty', '~> 0.16.2'
gem 'redis', '~> 4.1.3'

group :test do
  gem 'rspec', '~> 3.7.0'
  gem 'rack-test', '~> 0.8.3'
  gem 'webmock', '~> 3.3.0'
  gem 'timecop', '~> 0.9.1'
end
